### ISSUE TITLE
Pretrained model on Clavin does not work well

### ISSUE THREAD

**Issue by chenfengxu714** [nickgkan/3d_diffuser_actor#10]
Dear authors, congratulations for this great work! I am trying to reproduce the result yet got stuck at evaluation. I used your provided pre-trained model yet I got quite bad performance (almost zero success rate). I think I must miss something. Basically I follow your instruction yet I got the results as below. Could you provide me some hints？

Best regards

0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 1
14 0
15 0
16 0
17 0
18 0
19 1
20 0
21 1
22 0
23 0
24 0
25 0
26 0
27 0
28 0
29 0
30 0
31 0
32 0
33 1
34 1
35 0
36 0
37 0
41 0
38 0
39 0
43 0
40 0

**Comment by twke18** [comment]
Hi, thanks for your interest!

Would you like to provide more information about your local setup?

For your reference, we provided our training and testing log in [this post](https://github.com/nickgkan/3d_diffuser_actor/issues/5).  Could you confirm that your have set up the CALVIN environment correctly, and use [this script](https://github.com/nickgkan/3d_diffuser_actor/blob/master/scripts/test_trajectory_calvin.sh) for evaluating the released model?

**Comment by twke18** [comment]
The bad performance could result from the recent update of our model.  The default argument of `quaternion_format` becomes [`xyzw`](https://github.com/nickgkan/3d_diffuser_actor/blob/ba9c8f6cb1c8d027b7f3da36f63f43b943fdf2d3/online_evaluation_rlbench/evaluate_policy.py#L72), however, the CALVIN simulation considers `wxyz` quaternion.  Sorry that we forgot to update training and testing scripts on CALVIN accordingly.

**Comment by chenfengxu714** [comment]
Nice, it works. Thanks for your suggestion!

**Comment by cognaclee** [comment]
Dear authors, congratulations on this great work!  I encountered the same issue while testing the pretrained model you provided. I have set quaternion_format = wxyz, and the results I obtained are as follows:
task: use the switch to turn off the light bulb
1/5: 21.4% | 2/5: 1.1% | 3/5: 0.0% | 4/5: 0.0% | 5/5: 0.0%  ||
task: push the sliding door to the right side
1/5 : 21.3% | 2/5 : 1.1% | 3/5 : 0.0% | 4/5 : 0.0% | 5/5 : 0.0% ||

What could be the possible reason? Could you give me some hints?

**Comment by nickgkan** [comment]
Hi @cognaclee, please make sure to check the steps @twke18 mentioned above.
