### ISSUE TITLE
Instructions format

### ISSUE THREAD

**Issue by dennisushi** [nickgkan/3d_diffuser_actor#14]
Hi, I see the CALVIN instructions format differs from the RL bench one. 

CALVIN has 'text' and 'embeddings' fields. Meanwhile the RL bench ones are Dict[Taskname, Dict[Number, Embeddings]]

I am guessing the Number corresponds to a particular variation or possible embedding - can you confirm which of the two it is? Or is it defining a sequence of instructions? 

If a task has 5 possible captions, would those embeddings be separate entries within the dict, or would they be stacked in the final embeddings?

**Comment by twke18** [comment]
Hi,

On RLBench, each variation can be described in different ways.  The `embeddings` denotes a tensor of shape (num_descriptions, text_len, channel_dim).  If you would like to know how the `embeddings` is computed, you can see [this script](https://github.com/zhouxian/act3d-chained-diffuser/blob/5004650a9771e7618f24f36a876bcb38e0fc068a/data_preprocessing/preprocess_instructions.py#L159C13-L159C43) for details.  During [training](https://github.com/nickgkan/3d_diffuser_actor/blob/e576b69daec958c9706865b662b79bb068170220/datasets/dataset_engine.py#L187)/[testing](https://github.com/nickgkan/3d_diffuser_actor/blob/e576b69daec958c9706865b662b79bb068170220/utils/utils_with_rlbench.py#L157), we randomly sample a description for each variation.

On CALVIN, we do not use the `embeddings` provided by the official repo, but compute the `embeddings` in a similar manner as RLBench.  The official repo seems to apply global pooling on the features of each description, resulting in a tensor of shape (num_descriptions, 1, channel_dim).  We do not apply global pooling and generate a tensor of shape (num_description, 1, channel_dim).  Only one description is given for each task during training and testing on CALVIN.

**Comment by dennisushi** [comment]
Thanks
