### ISSUE TITLE
data loader for ABC_D

### ISSUE THREAD

**Issue by Cherryjingyao** [nickgkan/3d_diffuser_actor#16]
when i running the train code ,it crashed when load the data;
Device count 4
Gripper workspace size: [0.66333743 0.59459641 0.39931523]
Logging: /pfs-data/code/3d_diffuser_actor/train_logs/Planner_Calvin/diffusion_taskABC_D-C192-B30-lr3e-4-DI1-20-H3-DT25-backboneclip-S256,256-R1-wd5e-3
Available devices (CUDA_VISIBLE_DEVICES): None
Device count 4
Device count 4
Can't find dataset folder data/calvin/packaged_ABC_D/training/D+0
episodes num 3
Created dataset from data/calvin/packaged_ABC_D/training with 17870
Can't find dataset folder data/calvin/packaged_ABC_D/validation/A+0
Can't find dataset folder data/calvin/packaged_ABC_D/validation/B+0
Can't find dataset folder data/calvin/packaged_ABC_D/validation/C+0
episodes num 1
Created dataset from data/calvin/packaged_ABC_D/validation with 1087
Can't find dataset folder data/calvin/packaged_ABC_D/training/D+0
episodes num 3
Created dataset from data/calvin/packaged_ABC_D/training with 17870
Can't find dataset folder data/calvin/packaged_ABC_D/validation/A+0
Can't find dataset folder data/calvin/packaged_ABC_D/validation/B+0
Can't find dataset folder data/calvin/packaged_ABC_D/validation/C+0
episodes num 1
Created dataset from data/calvin/packaged_ABC_D/validation with 1087
Can't find dataset folder data/calvin/packaged_ABC_D/training/D+0
episodes num 3
Created dataset from data/calvin/packaged_ABC_D/training with 17870
Can't find dataset folder data/calvin/packaged_ABC_D/validation/A+0
Can't find dataset folder data/calvin/packaged_ABC_D/validation/B+0
Can't find dataset folder data/calvin/packaged_ABC_D/validation/C+0
episodes num 1
Created dataset from data/calvin/packaged_ABC_D/validation with 1087
Can't find dataset folder data/calvin/packaged_ABC_D/training/D+0
episodes num 3
Created dataset from data/calvin/packaged_ABC_D/training with 17870
Can't find dataset folder data/calvin/packaged_ABC_D/validation/A+0
Can't find dataset folder data/calvin/packaged_ABC_D/validation/B+0
Can't find dataset folder data/calvin/packaged_ABC_D/validation/C+0
episodes num 1
Created dataset from data/calvin/packaged_ABC_D/validation with 1087
Model parameters: 9751498
Model parameters: 9751498
Model parameters: 9751498
Model parameters: 9751498
  0%|                                                                                                       | 0/600000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/pfs-data/code/3d_diffuser_actor/main_trajectory_calvin.py", line 205, in <module>
    train_tester.main(collate_fn=traj_collate_fn)
  File "/pfs-data/code/3d_diffuser_actor/engine.py", line 150, in main
    sample = next(iter_loader)
  File "/data/mamba/envs/robodiff/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/data/mamba/envs/robodiff/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/data/mamba/envs/robodiff/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/data/mamba/envs/robodiff/lib/python3.9/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/mamba/envs/robodiff/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/mamba/envs/robodiff/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/mamba/envs/robodiff/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/pfs-data/code/3d_diffuser_actor/datasets/dataset_calvin.py", line 161, in __getitem__
    instr = torch.as_tensor(self._instructions[instr_ind])
IndexError: list index out of range

  0%|                                        

by the way ,when i used the debug dataset it run normally

**Comment by twke18** [comment]
Hi,

It seems that errors are raised [at these lines](https://github.com/nickgkan/3d_diffuser_actor/blob/e576b69daec958c9706865b662b79bb068170220/datasets/dataset_calvin.py#L158-L160) due to incorrect instruction indices.  The instruction indices denote the [iteration order](https://github.com/nickgkan/3d_diffuser_actor/blob/e576b69daec958c9706865b662b79bb068170220/data_preprocessing/package_calvin.py#L283) when packaging calvin demonstrations into `.dat` files.

Have you tried our provided [instructions](https://github.com/nickgkan/3d_diffuser_actor/tree/master?tab=readme-ov-file#optional-encode-language-instructions)?  If you re-computed the instruction embeddings yourselves, probably you can check if the instruction embeddings is a tensor of shape `(17870, text_length, channel_dim)`?

**Comment by twke18** [comment]
Hi,

We also have noticed the high variance of our results.  We found that by setting `num_history=1` (don't use history), the results are better and more stable.

We follow mostly the same training setup, using 6 A100 gpus.  We test the checkpoint at the 65K iteration with 3 random seeds.  The followings are the results:
```
Load 1000/1000 episodes...
1/5 : 94.4% | 2/5 : 80.2% | 3/5 : 64.5% | 4/5 : 50.9% | 5/5 : 40.0% ||
---
Load 1000/1000 episodes...
1/5 : 92.9% | 2/5 : 80.4% | 3/5 : 68.0% | 4/5 : 55.6% | 5/5 : 42.7% ||
---
Load 1000/1000 episodes...
1/5 : 94.1% | 2/5 : 80.2% | 3/5 : 66.2% | 4/5 : 53.3% | 5/5 : 41.0% ||
```

@fengxiuyaun, probably you can also try this setup if interested.

**Comment by fengxiuyaun** [comment]
> Hi,
> 
> We also have noticed the high variance of our results. We found that by setting `num_history=1` (don't use history), the results are better and more stable.
> 
> We follow mostly the same training setup, using 6 A100 gpus. We test the checkpoint at the 65K iteration with 3 random seeds. The followings are the results:
> 
> ```
> Load 1000/1000 episodes...
> 1/5 : 94.4% | 2/5 : 80.2% | 3/5 : 64.5% | 4/5 : 50.9% | 5/5 : 40.0% ||
> ---
> Load 1000/1000 episodes...
> 1/5 : 92.9% | 2/5 : 80.4% | 3/5 : 68.0% | 4/5 : 55.6% | 5/5 : 42.7% ||
> ---
> Load 1000/1000 episodes...
> 1/5 : 94.1% | 2/5 : 80.2% | 3/5 : 66.2% | 4/5 : 53.3% | 5/5 : 41.0% ||
> ```
> 
> @fengxiuyaun, probably you can also try this setup if interested.

Hi, 
Thank you for sharing. I'm a bit confused about how to choose the iteration number (65K) and the random seed(3). Are there any criteria for selecting these two variables, or do we just have to test them one by one to see which one has a higher success rate?

**Comment by twke18** [comment]
Hi,

We use the same iteration number (65K) for training the model.  This parameter was chosen at the early development of this project, when we did a grid-search over the number of iterations (55K, 65K and 75K) and didn't observe big performance change.  For simplification, we just chose the iteration number of 65K for our experiments.

We evaluated the same checkpoint 3 times on the 1000 instruction chains using different random seeds.  As you can see, the variance of our evaluation results is small.

**Comment by lihao0374** [comment]
> > Hi,
> > We also have noticed the high variance of our results. We found that by setting `num_history=1` (don't use history), the results are better and more stable.
> > We follow mostly the same training setup, using 6 A100 gpus. We test the checkpoint at the 65K iteration with 3 random seeds. The followings are the results:
> > ```
> > Load 1000/1000 episodes...
> > 1/5 : 94.4% | 2/5 : 80.2% | 3/5 : 64.5% | 4/5 : 50.9% | 5/5 : 40.0% ||
> > ---
> > Load 1000/1000 episodes...
> > 1/5 : 92.9% | 2/5 : 80.4% | 3/5 : 68.0% | 4/5 : 55.6% | 5/5 : 42.7% ||
> > ---
> > Load 1000/1000 episodes...
> > 1/5 : 94.1% | 2/5 : 80.2% | 3/5 : 66.2% | 4/5 : 53.3% | 5/5 : 41.0% ||
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @fengxiuyaun, probably you can also try this setup if interested.
> 
> Hi, Thank you for sharing. I'm a bit confused about how to choose the iteration number (65K) and the random seed(3). Are there any criteria for selecting these two variables, or do we just have to test them one by one to see which one has a higher success rate?



> > Hi,
> > We also have noticed the high variance of our results. We found that by setting `num_history=1` (don't use history), the results are better and more stable.
> > We follow mostly the same training setup, using 6 A100 gpus. We test the checkpoint at the 65K iteration with 3 random seeds. The followings are the results:
> > ```
> > Load 1000/1000 episodes...
> > 1/5 : 94.4% | 2/5 : 80.2% | 3/5 : 64.5% | 4/5 : 50.9% | 5/5 : 40.0% ||
> > ---
> > Load 1000/1000 episodes...
> > 1/5 : 92.9% | 2/5 : 80.4% | 3/5 : 68.0% | 4/5 : 55.6% | 5/5 : 42.7% ||
> > ---
> > Load 1000/1000 episodes...
> > 1/5 : 94.1% | 2/5 : 80.2% | 3/5 : 66.2% | 4/5 : 53.3% | 5/5 : 41.0% ||
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @fengxiuyaun, probably you can also try this setup if interested.
> 
> Hi, Thank you for sharing. I'm a bit confused about how to choose the iteration number (65K) and the random seed(3). Are there any criteria for selecting these two variables, or do we just have to test them one by one to see which one has a higher success rate?

Hello, can you reproduce the results in the paper? @fengxiuyaun

**Comment by fengxiuyaun** [comment]
> > > Hi,
> > > We also have noticed the high variance of our results. We found that by setting `num_history=1` (don't use history), the results are better and more stable.
> > > We follow mostly the same training setup, using 6 A100 gpus. We test the checkpoint at the 65K iteration with 3 random seeds. The followings are the results:
> > > ```
> > > Load 1000/1000 episodes...
> > > 1/5 : 94.4% | 2/5 : 80.2% | 3/5 : 64.5% | 4/5 : 50.9% | 5/5 : 40.0% ||
> > > ---
> > > Load 1000/1000 episodes...
> > > 1/5 : 92.9% | 2/5 : 80.4% | 3/5 : 68.0% | 4/5 : 55.6% | 5/5 : 42.7% ||
> > > ---
> > > Load 1000/1000 episodes...
> > > 1/5 : 94.1% | 2/5 : 80.2% | 3/5 : 66.2% | 4/5 : 53.3% | 5/5 : 41.0% ||
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @fengxiuyaun, probably you can also try this setup if interested.
> > 
> > 
> > Hi, Thank you for sharing. I'm a bit confused about how to choose the iteration number (65K) and the random seed(3). Are there any criteria for selecting these two variables, or do we just have to test them one by one to see which one has a higher success rate?
> 
> > > Hi,
> > > We also have noticed the high variance of our results. We found that by setting `num_history=1` (don't use history), the results are better and more stable.
> > > We follow mostly the same training setup, using 6 A100 gpus. We test the checkpoint at the 65K iteration with 3 random seeds. The followings are the results:
> > > ```
> > > Load 1000/1000 episodes...
> > > 1/5 : 94.4% | 2/5 : 80.2% | 3/5 : 64.5% | 4/5 : 50.9% | 5/5 : 40.0% ||
> > > ---
> > > Load 1000/1000 episodes...
> > > 1/5 : 92.9% | 2/5 : 80.4% | 3/5 : 68.0% | 4/5 : 55.6% | 5/5 : 42.7% ||
> > > ---
> > > Load 1000/1000 episodes...
> > > 1/5 : 94.1% | 2/5 : 80.2% | 3/5 : 66.2% | 4/5 : 53.3% | 5/5 : 41.0% ||
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @fengxiuyaun, probably you can also try this setup if interested.
> > 
> > 
> > Hi, Thank you for sharing. I'm a bit confused about how to choose the iteration number (65K) and the random seed(3). Are there any criteria for selecting these two variables, or do we just have to test them one by one to see which one has a higher success rate?
> 
> Hello, can you reproduce the results in the paper? @fengxiuyaun

I didn't conduct any further experiments due to a lack of time. Did you manage to reproduce it?
