### ISSUE TITLE
RLBench Training Data Packaged format 

### ISSUE THREAD

**Issue by richielo** [nickgkan/3d_diffuser_actor#20]
Hello, thanks for open-sourcing the code. I am trying to train the model with my own RLBench data. But I can't seem to locate the script to convert the data to the `.dat` format. Can you point me to the relevant script? I see there is this script from one of the linked projects: https://github.com/zhouxian/act3d-chained-diffuser/tree/main/data_preprocessing. But I am not sure if that is the correct one. Thanks a lot!

**Comment by twke18** [comment]
Hi,

We upload the python scripts for [re-rendering high-resolution camera views](https://github.com/nickgkan/3d_diffuser_actor/blob/master/data_preprocessing/rerender_highres_rlbench.py) and [packaging episodes into `.dat` files](https://github.com/nickgkan/3d_diffuser_actor/blob/master/data_preprocessing/package_rlbench.py).  You can check [DATA_PREPARATION_RLBENCH.md](https://github.com/nickgkan/3d_diffuser_actor/blob/master/docs/DATA_PREPARATION_RLBENCH.md#optional-re-render-trainingvalidation-episodes-in-higher-resolution) for details.
