### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by MaximilianToelle** [nickgkan/3d_diffuser_actor#21]
Hey, 

Thanks for your amazing work! I want to point out a current installation dependency problem: 

pip install dgl -f https://data.dgl.ai/wheels/cu116/dgl-1.1.3%2Bcu116-cp38-cp38-manylinux1_x86_64.whl installs dgl version 2.1.0 and also torch version 2.2.2. This in itself is a problem as dgl version 2.1.0 only supports torch versions 2.0.0/1, 2.1.0/1/2, 2.2.0/1. 

On the other hand, your environment.yaml file depends on pytorch 1.13.1, which does not work with dgl 2.1.0. In addition, pytorch 1.13.1 does not work with torchdata 0.7.1. However, it seems that you need torchdata>0.5.1, which is the last version that is compatible with pytorch 1.13.1. 

What worked for me was to install torch 2.1.0 and update torchvision to 0.16 after having installed the newest dgl version using your command. Maybe your intent was to install dgl 1.1.3, which supports pytorch 1.13.1, but I think your pip install link should then be https://data.dgl.ai/wheels/dgl-1.1.3-cp38-cp38-manylinux1_x86_64.whl.

**Comment by pawanw17** [comment]
I have faced this issue too... Ended up using dgl v2.1.0 with some workarounds here and there

**Comment by twke18** [comment]
Hi,

The EDIT 2 suggested by @pawanw17 works! Thanks for the suggestion and we will update the README accordingly.
