### ISSUE TITLE
Training cost on the RLBench Dataset.

### ISSUE THREAD

**Issue by siaoliu** [nickgkan/3d_diffuser_actor#22]
Hi,  Thanks for your wonderful work!
I would like to inquire about the training cost on the RLBench dataset. Does the model have significant efficiency advantages compared to the PerAct.

**Comment by twke18** [comment]
Hi,

Yes, our model is much more efficient than PerAct.  Using the same setup as PerAct, it takes us 6.5 days for training our model, while, PerAct needs a training time of 16 days.  Currently, our code base is bottlenecked by IO, which need some engineering effort to improve.

**Comment by aopolin-lv** [comment]
> Hi,
> 
> Yes, our model is much more efficient than PerAct. Using the same setup as PerAct, it takes us 6.5 days for training our model, while, PerAct needs a training time of 16 days. Currently, our code base is bottlenecked by IO, which need some engineering effort to improve.

Hi, 3d-diffuser-policy is an excellent work!
I am curious what gpus were used to train for the 6.5-day training time? Is it 8*v100- 16g?
