### ISSUE TITLE
Using Offline Image Encoding and the Necessity of Data Augmentation for Trajectory Prediction

### ISSUE THREAD

**Issue by LemonWade** [nickgkan/3d_diffuser_actor#24]
Hello , thank you for your efforts , it has been instrumental for my research.

1. Frozen Image Encoder with Online Encoding: I noticed that the image encoder is frozen during training and utilizes online encoding. I am curious to know if there is a possibility to switch to offline image encoding before training begins? This might potentially improve training speed by reducing the computational overhead during each training epoch. Could you provide some insights on whether this would be feasible and beneficial?

2. Data Augmentation for Trajectory Prediction: Additionally, the model employs data augmentation techniques for images while predicting trajectory differences. Given that the output is focused on trajectory differences, I am wondering about the effectiveness and necessity of image data augmentation in this context.

I appreciate any guidance or explanations you can provide on these topics, as they will greatly aid in optimizing my use of your model for better performance and understanding.

**Comment by twke18** [comment]
Hi,

1. We didn't observe performance gain with/without tuning the image encoder weights.  We thus froze them to speed up training.  I believe "which image encoder to use" is still an open question.  We found that CLIP works the best in this project. 
2. We found that performance dropped without data augmentation.  Our 3D Diffuser Actor takes input as 3D-lifted  2D feature maps.  Augmenting 2D images helps the model not to overfit some feature patterns, and increases the evaluation performance.

**Comment by LemonWade** [comment]
Thank you for your response. I've noticed that within the PerAct dataset, episodes belonging to the same task and variant do not always have identical KeyPoses; some episodes might have an additional KeyPose. Would these instances be considered noisy data? Thank you in advance for your clarification!

**Comment by twke18** [comment]
Hi,

The definition of keypoints are heuristic.  It's consider the continuity of end-effector motion.  You can see Section A in our Appendix.  Also, here is the [code](https://github.com/zhouxian/act3d-chained-diffuser/blob/5004650a9771e7618f24f36a876bcb38e0fc068a/utils/utils_with_rlbench.py#L909) for keypoint discovery on RLBench.

**Comment by LemonWade** [comment]
Thank you for your response. I noticed that in the `eval_peract` file, the `quaternion format is set as wxyz`, whereas in the `train_keypose_peract` file, it is set as `xyzw`. Could this be a typographical error?

**Comment by twke18** [comment]
Hi,

Please see the discussion here (#3 )

**Comment by LemonWade** [comment]
Thank you for your response. I have noticed that there are multiple choices for the graphical encoders in your work. Have you tested them all to conclude that the frozen CLIP is your best encoder?

**Comment by nickgkan** [comment]
Hi, out of the small set of encoders we tried we concluded that CLIP works the best. There are still numerous choices of encoders we didn't consider though.
