### ISSUE TITLE
the question about "flash-attn"

### ISSUE THREAD

**Issue by csufangyu** [nickgkan/3d_diffuser_actor#27]
thanks for your good job!!!!

I have a question about "flash-attn". In your paper, you use the Nvidia 32GB V100 GPU to implement experiments, but the flash-atten is not supported by V100. How do you solve it?  Since I only have the V100, this is very frustrating for me.

**Comment by twke18** [comment]
Hi,

Sorry for the confusion.  We tried flash attention at some point to reduce the computation overhead during testing, but do not use it at the current version of the code base.  You can simply commented out [this line](https://github.com/nickgkan/3d_diffuser_actor/blob/2ab63276a29464a4b6b223ea5472df6100984db8/diffuser_actor/utils/converter.py#L8) and remove `MultiheadFlashAttention` in [this line](https://github.com/nickgkan/3d_diffuser_actor/blob/2ab63276a29464a4b6b223ea5472df6100984db8/diffuser_actor/utils/converter.py#L175).
