### ISSUE TITLE
How do you debugged the code?

### ISSUE THREAD

**Issue by ZXP-S-works** [nickgkan/3d_diffuser_actor#29]
Hi nickgkan,

Thanks for the good work!

I am curious how you debug the code since we ran the code by a bash script with torchrun, which is a distributed GPU training.

Do you use VScode or Pycharm? Do you run the Python script alone for debugging?

Thank you for your time!

Best,
XP

**Comment by twke18** [comment]
Hi,

We mainly use `ipdb` module for debugging, with which we can print out the numerical values of tensors on the fly.  We also use a lot of matplotlib to visualize the 3D points.

**Comment by ZXP-S-works** [comment]
Hi twke18,

Thanks for the quick reply, I will take a look at ipdb. I also managed to use Pycharm to debug. I used `torch.distributed.run --nproc_per_node=1 --master_port=1234 main_trajectory.py --...`.

Best,
XP
