### ISSUE TITLE
Questions about model and input data

### ISSUE THREAD

**Issue by ljy1234-special** [nickgkan/3d_diffuser_actor#32]
Hi，There are some data form and modeling issues as it has not been reproduced yet and I've only just looked at the code：
1. Is the input to the model in the form of the current action `a coordinate` in discrete space or `an index` of the action similar to `PerAct`? If it is a coordinate in discrete space, and continuous discrete coordinates are not easily regressed accurately, how can using a diffusion model ensure that the predicted coordinates can be regressed? If it's an index, but don't see a function like PerAct's `choose_highest_action` in the code, etc.?
2. May I ask if you calculate the `Q-value` of the action in your method?

**Comment by nickgkan** [comment]
Hi,
There's no action quantization in our model and no Q-value/next-best action map computation. 3D Diffuser Actor is a diffusion model and denoises (trajectories of) actions directly in the continuous space. Please refer to our paper and this link https://github.com/nickgkan/3d_diffuser_actor/blob/master/docs/OVERVIEW.md for details.
