### ISSUE TITLE
How to accelerate the eval process

### ISSUE THREAD

**Issue by nightsky-nostar** [nickgkan/3d_diffuser_actor#33]
I run the command `bash online_evalution_rlbench/eval_gnfactor.sh`. This took a lot of time. 
I tried to set `headless=True` when initial the Environment class from `rlbench.environment`. However, that did not make a significant effect.

Is there any way to speed up the eval process？
Thank you in advance!

**Comment by nickgkan** [comment]
Hi, what part of the evaluation is slow? The model may take a second before it moves until the next keypose. Make sure you run this on a GPU. I'm not sure if there is a way not to display graphics at all so that it's faster, we didn't consider such an alternative.
