### ISSUE TITLE
Question on Epochs and training Iterations

### ISSUE THREAD

**Issue by pawanw17** [nickgkan/3d_diffuser_actor#36]
Hi, thanks for the great work!

I had a doubt regarding training iterations and epochs, The paper mentions your training setup with 1.6e4 epochs (for peract). However the code uses training iterations, is there a formula to go from iterations to epochs or are they used interchangeably? this will help me tune in for better time estimations.

**Comment by twke18** [comment]
Hi,

Thanks for your interest!  Sorry for the confusion about the training iterations and epochs.  We estimate the epoch based on the formula of `total_iteration / total_num_demonstration * num_demonstration_per_batch`, which is `6e5 / 1800 * 48 = 1.6e4` on PerAct.  We observe the reported epoch on CALVIN may not be correct, which will be updated in the paper.
