### ISSUE TITLE
evaluation on other RLBench tasks

### ISSUE THREAD

**Issue by ubless607** [nickgkan/3d_diffuser_actor#39]
Thank you for sharing your amazing work.
If I want to evaluate the model's performance on other RLBench tasks (other than 18 tasks tested on PerAct), do I need to retrain the model from scratch?

**Comment by nickgkan** [comment]
Hi, thanks for your interest in our work! For a fair evaluation, yes, you would need to retrain the model on the new tasks. In the past we trained this model on many RLBench tasks beyond the 18 and the performance was very good, but our final results are on the benchmarked 18 tasks for direct comparison. Good luck and let us know how it goes!
