### ISSUE TITLE
Real Robot Dataset Release

### ISSUE THREAD

**Issue by oym1994** [nickgkan/3d_diffuser_actor#40]
Hi, thanks for your great job! Will you also release the real-robot dataset?    Many thanks if possible.

**Comment by twke18** [comment]
Hi,

We indeed have the demos for our real-world experiments.  However, since the scene, camera and robot configuration differ between labs, our collected demos might not be useful for others.  We'd encourage you to collect your own real-world demos.

**Comment by oym1994** [comment]
Got it! thanks for your response!  Another question, if the point cloud are transformed to the robot frame,  will it be possible to use the data across different robot configuration? Which means data from different labs can be trained together and then deployed in different robots.

**Comment by nickgkan** [comment]
I think that could be possible even without transforming the point clouds, but for sure transforming them would facilitate learning and transfer. There are already datasets that merge real-robot datasets from different labs, like OpenX and DROID.
