### ISSUE TITLE
Discrepancy between train/eval scripts

### ISSUE THREAD

**Issue by jesbu1** [nickgkan/3d_diffuser_actor#42]
To evaluate the pre-trained model, the current evaluation script expects `wxyz` as the quaternion format as that is what the pre-trained model ckpt is trained on (https://github.com/jesbu1/3d_diffuser_actor/blob/master/online_evaluation_rlbench/eval_peract.sh#L21)

However, the script to train a new model on peract data uses `xyzw` as the quaternion format https://github.com/jesbu1/3d_diffuser_actor/blob/master/scripts/train_keypose_peract.sh#L14. If you were to train the model and evaluate with both given scripts, the success rate is 0. Perhaps a warning message should be put somewhere or an additional script should be added?

**Comment by twke18** [comment]
Hi,

Thanks for the reminder.  We already have a notification in our README (https://github.com/nickgkan/3d_diffuser_actor?tab=readme-ov-file#evaluate-the-pre-trained-weights).  We'd consider to make the message more salient.

**Comment by jesbu1** [comment]
I think it'd be best to put a very visible comment in the evaluation script itself so users don't forget after training something

**Comment by nickgkan** [comment]
I added a comment in the eval scripts, thanks for the suggestion.
