### ISSUE TITLE
Can't find dataset folder

### ISSUE THREAD

**Issue by GuanxingLu** [nickgkan/3d_diffuser_actor#44]
Great work! I have downloaded your packaged RLBench demonstrations from huggingface, and unzipped it without error. However, when I try to run `bash scripts/train_trajectory_gnfactor.sh`, the program throws lots of "Can't find dataset folder xxx" (See figure 1), but the training process seems to keep on running (See figure 2). Is this normal?
<img width="1157" alt="1722779787676" src="https://github.com/user-attachments/assets/2339b09a-c5e5-4715-821b-9b15d7e4a371">
<img width="1157" alt="1722779733896" src="https://github.com/user-attachments/assets/7a39f3cb-9ee7-4682-82ef-4d82bb5e09fe">

**Comment by nickgkan** [comment]
Yes, we search for a range of numbers for variations and not of all the numbers correspond to actual existing variation ids.
As you see in the first screenshot, the total number of training samples in your case is 200, which is exactly as expected (10 tasks * 20 demos).

**Comment by GuanxingLu** [comment]
I see, thanks for your prompt reply!
