### ISSUE TITLE
About the  Preparing RLBench dataset.

### ISSUE THREAD

**Issue by Zhangwenyao1** [nickgkan/3d_diffuser_actor#46]
Thanks for your great work!
Are there any annotations(segmentation mask, depth) in the Preparing RLBench dataset?

**Comment by Zhangwenyao1** [comment]
Hi, @buttomnutstoast @jesbu1 @nickgkan.
In the RLbench datasets, I found you load the image and point cloud from the processed dataset.
What can I do if I want to project the point cloud to the depth map and it seems no intrtic and extrinsic matrix in the datasets folder and processed dataset file (Peract_packaged.zip).

**Comment by nickgkan** [comment]
This is the script we use for packaging the data https://github.com/nickgkan/3d_diffuser_actor/blob/master/data_preprocessing/package_rlbench.py. The extrinsics and intrinsics can be found inside the env code, e.g. here https://github.com/nickgkan/3d_diffuser_actor/blob/master/utils/utils_with_rlbench.py.
