### ISSUE TITLE
Code Confusion

### ISSUE THREAD

**Issue by windboy6** [nickgkan/3d_diffuser_actor#49]
Hi,

I'm not sure if I'm understanding this accurately. When using trajectories, this code represents the coding for each time step.

Can you explain what this code represents when using keypose?https://github.com/nickgkan/3d_diffuser_actor/blob/4faf00bdf89a3b3d07e266a59a28f9fbd02c7844/diffuser_actor/trajectory_optimization/diffuser_actor.py#L527-L529

**Comment by nickgkan** [comment]
Hi,

The codebase treats keyposes as trajectories of length 1. So we just add the trajectory time step encoding in this case as well. It's not useful when the trajectory's length is 1, but it doesn't harm. This unifies the code for all cases.

**Comment by windboy6** [comment]
I see, thanks for the clear explanation.
