### ISSUE TITLE
How to generate the RLBench dataset by ourselves

### ISSUE THREAD

**Issue by ggggfff1** [nickgkan/3d_diffuser_actor#52]
The RLBench dataset is too large to download. If we can generate the dataset by ourselves like peract? 
It also a good way to provide a smaller dataset to instead [this one](https://huggingface.co/katefgroup/3d_diffuser_actor/blob/main/Peract_packaged.zip), which only contain one or two tasks for testing.

**Comment by nickgkan** [comment]
Hi, these two steps are what you need https://github.com/nickgkan/3d_diffuser_actor/blob/master/docs/DATA_PREPARATION_RLBENCH.md#optional-re-render-trainingvalidation-episodes-in-higher-resolution

**Comment by ggggfff1** [comment]
"Hi, I think this method works for creating our test dataset. Does it also work for the training dataset?"

**Comment by nickgkan** [comment]
To make sure we refer to the same method 
![image](https://github.com/user-attachments/assets/f9dbf2d2-68a4-4566-a431-7a5110875811)

It works for all sets.

**Comment by ggggfff1** [comment]
Thank you for your patient reply. 
OK, I understand your point. My question is, the zip file is too large to download. Can we create the training dataset using RLBench on our platform instead? Or, is it possible to download the dataset for each task separately?

**Comment by nickgkan** [comment]
I believe there is a misunderstanding. I mean, only run those two steps I pasted above. This way you won't have to download the large zip file you mentioned in your first message.

Then, using the link I pasted, you have to download the episodes per task. So you can just download fewer tasks if you want.

Lastly, if even those zip files are too large for you, check the PerAct repository to see how to generate episodes from scratch. But this way your results may not be comparable to others, unless you generate the exact same dataset.

**Comment by ggggfff1** [comment]
Ohh, thank you for you help! I have solved this problem
