### ISSUE TITLE
RLbench training using multiple GPUs

### ISSUE THREAD

**Issue by BofangJia** [nickgkan/3d_diffuser_actor#53]
Hi,Thank you very much for your work!

While replicating the experiments, I encountered an issue related to the Blosc buffer when decompressing data. The error message I received is as follows: blosc_extension.error: Error 33423360 : not a Blosc buffer or header info is corrupted(Every time I go into 'Val' I stop working)

I was wondering if you had encountered a similar issue during your work.   If so, could you share how you resolved it?
![1](https://github.com/user-attachments/assets/cd13963c-468d-46bd-a1c0-0e0ed88e0865)
![2](https://github.com/user-attachments/assets/0eb00c5e-84fb-4dd5-a6d8-29bc08152c4b)
![3](https://github.com/user-attachments/assets/ed0b6934-0812-4752-8492-a8afaddbb226)
![4](https://github.com/user-attachments/assets/40c57242-3970-48b9-b437-ab4c5c3d9a3d)

**Comment by nickgkan** [comment]
Hi, we never encountered this issue. From the description, it seems that some file is corrupted? Did you download the packaged data?
