### ISSUE TITLE
Inconsistency between the paper and code regarding time step sampling during training

### ISSUE THREAD

**Issue by HuskyKingdom** [nickgkan/3d_diffuser_actor#55]
Hi, thank you for the great work!

During reproducing, I have encountered a issue such that, in the paper, it is mentioned that:

"During training, we randomly sample a time step t and a diffusion step i and add noise ϵ = (ϵ_loc, ϵ_rot) to a ground-truth trajectory τ_t^0."

However, in the DiffuserActor class, particularly in the forward method, the implementation appears to only randomly sample a diffusion step i for the entire ground-truth trajectory, without randomly sampling a specific time step t. The noise is then added to the whole trajectory rather than a specific time step t, which seems inconsistent with the paper's description.

Code reference:
In forward:
```
# Sample a random timestep (i.e., diffusion step)
timesteps = torch.randint(
    0,
    self.position_noise_scheduler.config.num_train_timesteps,
    (len(noise),), device=noise.device
).long()

# Add noise to the entire clean trajectory
pos = self.position_noise_scheduler.add_noise(
    gt_trajectory[..., :3], noise[..., :3],
    timesteps
)
rot = self.rotation_noise_scheduler.add_noise(
    gt_trajectory[..., 3:9], noise[..., 3:9],
    timesteps
)
```

This code suggests that the noise is applied across all time steps of the trajectory based on a sampled diffusion step i, rather than sampling a specific time step t to apply the noise as described in the paper.

Could you clarify whether this is an intentional simplification in the implementation, or if the code needs to be adjusted to match the methodology described in the paper?

Thank you!

**Comment by nickgkan** [comment]
Hi,
I see the confusion, I think the paper writing is a bit unclear at this point. The code is correct.

τ_t^0 refers to a trajectory starting at timestep t. A batch of such trajectories is fetched by the data loader (randomly sampled from the training trajectories). Then, diffusion timesteps are randomly sampled, as in the snippet you pasted.

So the sentence in the paper should instead state that we randomly sample training trajectories and also randomly sample diffusion timesteps. We'll revise the writing in the next version to resolve this confusion.

**Comment by HuskyKingdom** [comment]
Thank you for the clarification, I am closing this issue now.
