### ISSUE TITLE
Gripper openness in observation

### ISSUE THREAD

**Issue by chereddy** [nickgkan/3d_diffuser_actor#57]
Hi,

I saw that the gripper history does not include gripper openness, but instead just includes position and rotation. Is there a reason for this?

`curr_gripper = curr_gripper[..., :7]`

**Comment by nickgkan** [comment]
Hi,

No, this is not something we ablated. In fact, the rotation information is also not used in the encoding of the current gripper. This may or may not be suboptimal, but we haven't experimented much.
