### ISSUE TITLE
Problem when running eval on rlbench 

### ISSUE THREAD

**Issue by rebecajohn** [nickgkan/3d_diffuser_actor#59]
Command used : bash online_evaluation_rlbench/eval_peract.sh

Loading model from train_logs/diffuser_actor_peract.pth
Gripper workspace
Gripper workspace size: [0.75823578 1.07414986 0.79873248]
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/teamspace/studios/this_studio/PyRep/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, webgl, xcb.

/commands/python: line 37: 40081 Aborted                 (core dumped) "$@"
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torchdata/datapipes/__init__.py:18: UserWarning: 
################################################################################
WARNING!
The 'datapipes', 'dataloader2' modules are deprecated and will be removed in a
future torchdata release! Please see https://github.com/pytorch/data/issues/1196
to learn more and leave feedback.
################################################################################

  deprecation_warning()

**Comment by nickgkan** [comment]
Hi,
We've had trouble running this script in headless mode as well. I would suggest that you run it on a PC with a display. Then, follow the instructions in our README to install CoppeliaSim/PyRep/RLBench.

**Comment by rebecajohn** [comment]
Hi ,
Thanks for the response. But I don't have NVIDIA GPU on my PC , i have H100 servers only.

**Comment by nickgkan** [comment]
In that case, I would recommend building a docker container where these libraries can be installed and compiled properly. Then, you can run this container on your cluster.

**Comment by rebecajohn** [comment]
Hi , while running nvidia-xconfig -a --use-display-device=None --virtual=1280x1024 inside docker conatiner , bash: nvidia-xconfig: command not found.

**Comment by ShawnXie1999** [comment]
> Hi , while running nvidia-xconfig -a --use-display-device=None --virtual=1280x1024 inside docker conatiner , bash: nvidia-xconfig: command not found.

I've also encountered this problem. So, how did you finally solve it?

**Comment by YukiFan** [comment]
Perhaps due to the installation of some new packages, my environment also encountered this issue when I ran the code again. I hope my experience may be helpful to you

Clean up all information about rlbench pyrep and CoppeliaSim
Reinstall according to the instructions provided by the author step by step, which is indeed useful
For rlbench, you can directly try installing it with this [link](https://github.com/MohitShridhar/RLBench/tree/peract)
Install OpenCV-Python headless
