### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by rainbow979** [nickgkan/3d_diffuser_actor#60]
Thanks for your great work. I'm trying to use 6 V100 with 32GBs to train the code. I have modified batch_size to 16. But GPUs are still out of memory.
I'm wondering what are GPUs you using to train.

**Comment by rainbow979** [comment]
And how long to train on the Calvin dataset

**Comment by twke18** [comment]
Hi,

We used 6~7 A100 Gpus (40 GB) for our calvin experiments, which takes around 24 hrs for training.

**Comment by rainbow979** [comment]
How many training iterations since the speed of A100 is different from V100?
Are there any results about training on whole trajectories for calvin dataset? The results of the paper are used keypose.

**Comment by nickgkan** [comment]
Around 80-100k iterations, please monitor the validation curves in tensorboard as a proxy.

We report results for predicting interpolated trajectories between keyposes. We haven't reported results without keyposes at all. We have been able to achieve similar performance without keyposes in the past, in unofficial experiments.
