### ISSUE TITLE
pkl file generated by the script is different

### ISSUE THREAD

**Issue by xiaohao9999** [nickgkan/3d_diffuser_actor#61]
Hello, 

The pkl file I generated using the following script is different in size from the one you provided.

`> python data_preprocessing/preprocess_rlbench_instructions.py  --tasks place_cups close_jar insert_onto_square_peg light_bulb_in meat_off_grill open_drawer place_shape_in_shape_sorter place_wine_at_rack_location push_buttons put_groceries_in_cupboard put_item_in_drawer put_money_in_safe reach_and_drag slide_block_to_color_target stack_blocks stack_cups sweep_to_dustpan_of_size turn_tap --output instructions.pkl`

![image](https://github.com/user-attachments/assets/9799e009-c565-453e-941a-3ab40a9d4da7)

![1726369953419](https://github.com/user-attachments/assets/8643237a-0c75-450a-b847-aede14b5979e)

Is this correct?

By the way, I would like to ask how these boundaries are defined.
> tasks/18_peract_tasks_location_bounds.json

> {
    "close_jar": [
        [
            -0.07010312378406525,
            -0.33692488074302673,
            0.761122465133667
        ],
        [
            0.525260329246521,
            0.40034544467926025,
            0.9308611154556274
        ]
    ],

**Comment by twke18** [comment]
Hi,

The `instructions.pkl` we provided is directly adopted from [Act3d repo](https://github.com/zhouxian/act3d-chained-diffuser?tab=readme-ov-file#dataset-generation), which contains more tasks than the ones used in PerAct.

The gripper location boundaries is defined as the minimum and maximum of gripper locations aggregated among all keyframes from all demonstrations for each task.  We calculate the minimum and maximum of `X, Y, Z` separately.

**Comment by xiaohao9999** [comment]
Hi,

Thank you for your timely reply!

Can you explain the boundary more clearly? I want to try another task, but it is not in the json file you gave me.

**Comment by twke18** [comment]
You can check [these lines](https://github.com/zhouxian/act3d-chained-diffuser/blob/5004650a9771e7618f24f36a876bcb38e0fc068a/data_preprocessing/compute_workspace_bounds.py#L80-L92) from the Act3D repo.  We follow the same procedure to obtain minimum and maximum bounds of gripper location.

**Comment by xiaohao9999** [comment]
OK, thanks a lot! This is useful!
