### ISSUE TITLE
Single view model modification

### ISSUE THREAD

**Issue by xiaohao9999** [nickgkan/3d_diffuser_actor#67]
Hi,

If I want to test the performance of the model in a single view, do I just need to modify the camera hyperparameters for training and inference? I only modified this, but many of the test results are 0.

Can you tell me if there is anything else that needs to be modified?
https://github.com/nickgkan/3d_diffuser_actor/blob/4faf00bdf89a3b3d07e266a59a28f9fbd02c7844/scripts/train_trajectory_peract.sh#L41

**Comment by nickgkan** [comment]
Hi,
This is our script for single-view experiments https://github.com/nickgkan/3d_diffuser_actor/blob/master/scripts/train_trajectory_gnfactor.sh.

Yes, you mainly need to change the --cameras argument.

**Comment by xiaohao9999** [comment]
😥Sorry, I forgot you also have a script for single-view testing. Thank you for your answer！
