### ISSUE TITLE
Inference speed of 3D Diffuser Actor

### ISSUE THREAD

**Issue by xiaohao9999** [nickgkan/3d_diffuser_actor#69]
Hi,

I noticed that the time reported in your paper is 600ms.

![image](https://github.com/user-attachments/assets/44d82b25-2799-466b-9ba0-3de4dad85924)

However, when I tested it with 3090, the result was nearly 2 seconds.
![image](https://github.com/user-attachments/assets/1ac1e9d6-8acc-42bb-9ed9-479d3591c919)

I tested the time from data input to output.
![image](https://github.com/user-attachments/assets/765edc56-7873-4337-b1b6-77b9f67c75d3)

**Comment by QazyBi** [comment]
Hello, I've encountered a similar issue while using this project. Any updates or potential solutions would be greatly appreciated.

**Comment by twke18** [comment]
Hi,

Please note that, as mentioned in the paper, the reported runtime is in CALVIN, where less camera views, smaller image resolution and fewer diffusion timesteps are used.

**Comment by AnshShah3009** [comment]
@xiaohao9999 Please look at this small fix [PR](https://github.com/nickgkan/3d_diffuser_actor/pull/50), It is possible that the model might not be using the GPU.

**Comment by xiaohao9999** [comment]
Hi, 

In fact, I have already set it up like this. As the author said, the running speed can indeed reach 600ms with less resource consumption.
