### ISSUE TITLE
Using custom data, and using real robot

### ISSUE THREAD

**Issue by dennisushi** [nickgkan/3d_diffuser_actor#7]
Hello,

Thank you for providing the training dataset. I noticed the dataset is in `.dat` format, and I was wondering if there are specific instructions available for generating data in this format.

For creating a new dataset using a real Panda robot, I understand from your guidance to refer to [this repository](https://github.com/zhouxian/franka). To ensure compatibility, it appears necessary to save the data in the same `.dat` format, including matching the data fields. Additionally, for generating a new `instructions.pkl` file, am I correct in assuming that we can follow the process outlined in the CALVIN example? I am assuming that as in your paper, 20 demonstrations would be enough. Should I capture the whole trajectory or just the keyframes? 

Could you please confirm these steps or provide further details if available? Are there other important considerations or instructions we should be aware of when creating and formatting a new dataset for this project?

Thank you for your assistance.

**Comment by nickgkan** [comment]
Hi @dennisushi, thanks for your interest!
First, regarding the dataset format, you can find an example [here](https://github.com/zhouxian/franka/blob/main/collect_demo.py#L223) or [here](https://github.com/zhouxian/act3d-chained-diffuser/blob/main/data_preprocessing/data_gen.py#L126).
For the instructions, you're right, you can follow the process outlined in CALVIN.
Depending on the task, you may need more or less demos. Based on our experience, 15 demos were enough for most of the real-world tasks we considered.
We recorded only the keyposes and trainrd the model to predict the next keypose only.
Good luck!

**Comment by dennisushi** [comment]
Thanks for the quick response!

**Comment by dennisushi** [comment]
Hi, I am struggling to reproduce the real-world results. I made a dataset of 14 demonstrations of the simplest task I could think off, reach object, moving the starting position of the robot and the position of the object in each demonstration. I trained the model for 600k steps as default. The position loss barely moved. Can you give any tips what may be wrong?

![image](https://github.com/nickgkan/3d_diffuser_actor/assets/30011340/71a145da-ab00-4b2a-971f-f38312cb274d)

For reference, this is what the demo's look like [ep0.zip](https://github.com/nickgkan/3d_diffuser_actor/files/14721055/ep0.zip), each having 4-6 keyposes depending on the positions (should the number of keyposes be the same across all?):

![ep0_1](https://github.com/nickgkan/3d_diffuser_actor/assets/30011340/b598b283-71cd-48cf-a5bc-d0476df3c302)
![ep0_4](https://github.com/nickgkan/3d_diffuser_actor/assets/30011340/76c930f9-4ae8-4794-a383-2aeebcb48e48)

The state data is collected as
```python
        gripper_trans = robot_arm.get_pose()[:3,3]
        gripper_quat = rotation_to_quaternion(robot_arm.get_pose()[:3,:3])
        gripper_open =  (not robot_arm.is_grasped())
        gripper_input = np.concatenate([gripper_trans, gripper_quat, [gripper_open]])
```

**Comment by twke18** [comment]
Hi,

In our experience, we would first check if the location bound is set up correctly.  For example, these are the location bounds for [RLBench](https://github.com/nickgkan/3d_diffuser_actor/blob/master/tasks/18_peract_tasks_location_bounds.json) and [CALVIN](https://github.com/nickgkan/3d_diffuser_actor/blob/master/tasks/calvin_rel_traj_location_bounds_task_ABC_D.json).  We would re-scale the position xyz to the range of [-1, 1].

Secondly, you can check if the point cloud and the end-effector pose is embedded in the same coordinate system.  One quick experiment for debugging is to train the [Act3D](https://github.com/nickgkan/3d_diffuser_actor/blob/master/scripts/train_act3d_peract.sh) baseline, which should give you a hint if the input/output are formatted correctly.

**Comment by dennisushi** [comment]
> you can check if the point cloud and the end-effector pose is embedded in the same coordinate system

So any external camera needs to be transformed to the same world frame as the grasp pose?


I had not put any bounds, I will try again with all these tips, thanks!
