### ISSUE TITLE
What are the precise compositions of the "action", "curr_gripper" and "trajectory"?

### ISSUE THREAD

**Issue by ZeyuPing** [nickgkan/3d_diffuser_actor#74]
Hi! Thank you for your great work! I wonder What are the precise compositions of the "action", "curr_gripper" and "trajectory"? Are they "next timestep's gripper pose", "gripper pose" and "t steps' gripper pose" respectly?

**Comment by nickgkan** [comment]
Hi,
Yes, your interpretation is close to the truth.

Action = next keypose
curr_gripper = gripper pose now (may also contain history)
trajectory = t gripper poses up to the next keypose

Hope that helps!
