### ISSUE TITLE
Performance difference in close jar task when reproduced

### ISSUE THREAD

**Issue by Ashnne** [nickgkan/3d_diffuser_actor#75]
Hi, thank you for your excellent work and code!

When we reproduced the 3D Diffuser Actor on RLBench with a single-view setting, we noticed some differences between our results and the provided checkpoint in close jar task. We saw that you mentioned using 4 GPUs with a training iteration of 600,000 for the GNFactor setup on RLBench. For our setup, we used 4 80GB H800 GPUs with the same number of iterations.

We used the original code cloned from GitHub and followed the steps in DATA_PREPARATION_RLBENCH.md to download the dataset. While we rearranged the episodes, we didn’t re-render them. Additionally, we fixed a bug in close_jar.py in RLBench, which was affecting the success rate for the “close jar” task.

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/d3088d90-87a6-4c2e-9bb4-ab28c4ea061f">

Could you please explain why the difference performance between the checkpoint we trained and downloaded from the huggging face, or something we forget or ignore results in the difference.

**Comment by nickgkan** [comment]
Hi,

By not re-rendering the images, does that mean that their size is 128x128? That could explain the difference.
There's also variance (that's why we evaluate three times), but the result or close_jar cannot be justified by variance.
