### ISSUE TITLE
Raw instructions for the features in "instructions.pkl"

### ISSUE THREAD

**Issue by qwerty863** [nickgkan/3d_diffuser_actor#8]
Hello,

Thank you for sharing your awesome work!

I've found that "instructions.pkl" has CLIP text features for instructions but not raw instructions.
How can we get the raw instructions as well? Any tips on getting the instructions?

Thank you in advance!

**Comment by nickgkan** [comment]
Hi @qwerty863,

Currently we don't provide the raw RLBench instructions but you can find them inside the corresponding task file, for example [here](https://github.com/MohitShridhar/RLBench/blob/peract/rlbench/tasks/basketball_in_hoop.py#L20).

For CALVIN they are downloaded with the dataset, if you follow the instructions we provide.

**Comment by qwerty863** [comment]
Thanks for your quick answer! I'll check that.
